### ISSUE TITLE
JokeAPI will be deprecated

### ISSUE THREAD

**Issue by Sv443** [ToastIT-dev/PoshBot.Joker#16]
Hi, I just found your repo through a Google search and saw that you still use the old version (v1.1) of my API, [JokeAPI](https://github.com/Sv443/JokeAPI). It will be deprecated by the end of June 2020 and you should migrate to the new version (v2.1), which you can find [here](https://sv443.net/jokeapi/v2).  
PS: would you be okay with me adding this repo to the list of dependents in the readme of JokeAPI and on the documentation page?

**Comment by Windos** [comment]
@Sv443 thanks for the heads up, and sorry it took so long to move over (thanks @Saggiehaim!)

Would be absolutely fine with being added to the list of dependents 😄
